import type { Metadata } from "next";
import Link from "next/link";
import { getServices } from "@/lib/data/services";
import { getSite } from "@/lib/data/site";
import { siteUrl } from "@/lib/seo";
import type { Service } from "@/lib/types/content";
import Faq from "@/components/ui/Faq";
import CtaBand from "@/components/sections/CtaBand";
import ScrollProgress from "@/components/ui/ScrollProgress";
import BackToTop from "@/components/ui/BackToTop";
import ServiceMarquee from "@/components/ui/ServiceMarquee";
import ServiceList from "@/components/ui/ServiceList";

const pageDescription =
  "Web app development, UI/UX design, custom CRM, e-commerce, API and backend work, business email setup, hosting, and AI automation — built end to end by one developer. Free 30-minute scoping call.";

export async function generateMetadata(): Promise<Metadata> {
  const site = await getSite();

  return {
  title: "Services — Web Apps, CRMs, E-Commerce, APIs & Automation",
  description: pageDescription,
  keywords: [
    "web development services",
    "full-stack developer for hire",
    "UI UX design services",
    "API development",
    "custom CRM development",
    "e-commerce development",
    "business email setup",
    "web hosting deployment",
    "AI automation services",
    "freelance web developer",
  ],
  alternates: { canonical: `${siteUrl}/services` },
  openGraph: {
    title: "Services — Software Development by Rahman",
    description:
      "End-to-end web development, design, and infrastructure services for businesses that care about quality.",
    url: `${siteUrl}/services`,
    type: "website",
    // Social image generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Services — Software Development by Rahman",
    description:
      "End-to-end web development, design, and infrastructure services for businesses that care about quality.",
    site: site.social.twitterHandle,
    creator: site.social.twitterHandle,
  },
  };
}

const buildJsonLd = (services: Service[]) => ({
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "@id": `${siteUrl}/services#page`,
  name: "Services — Rahman Software Developer",
  description: pageDescription,
  url: `${siteUrl}/services`,
  isPartOf: { "@id": `${siteUrl}/#website` },
  about: { "@id": `${siteUrl}/#business` },
  inLanguage: "en-US",
  mainEntity: {
    "@type": "ItemList",
    itemListElement: services.map((s, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: s.title,
      description: s.shortDesc,
      url: `${siteUrl}/services/${s.slug}`,
    })),
  },
});

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
    {
      "@type": "ListItem",
      position: 2,
      name: "Services",
      item: `${siteUrl}/services`,
    },
  ],
};

/** The three objections that stop a small business from hiring a freelancer. */
const guarantees = [
  {
    title: "Fixed, written quote",
    body: "You approve a scope and a number before any work starts. No hourly surprises, no scope creep invoices.",
  },
  {
    title: "You own everything",
    body: "Full source code in your own Git repo, plus deployment docs. Nothing is locked behind me.",
  },
  {
    title: "30 days of free fixes",
    body: "Anything I built that breaks after launch gets fixed at no cost for the first month.",
  },
];

export default async function ServicesPage() {
  const services = await getServices();
  const jsonLd = buildJsonLd(services);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <ScrollProgress />

      {/* ── Hero ────────────────────────────────────────────────────────── */}
      <div className="relative overflow-hidden pt-32 pb-16">
        <div className="aurora" aria-hidden="true" />
        <div className="grid-bg" aria-hidden="true" />

        <div className="relative mx-auto max-w-6xl px-6">
          <nav
            aria-label="Breadcrumb"
            className="mb-8 flex items-center gap-2 text-xs text-muted"
          >
            <Link href="/" className="transition-colors hover:text-fg">
              Home
            </Link>
            <span aria-hidden="true">/</span>
            <span className="text-fg">Services</span>
          </nav>

          <header className="max-w-3xl">
            <p className="mb-4 text-xs font-medium uppercase tracking-widest text-muted">
              What I Do
            </p>
            <h1 className="mb-6 font-display text-5xl font-bold leading-tight tracking-tight text-fg md:text-6xl">
              Services
            </h1>
            <p className="text-lg leading-relaxed text-muted">
              I work across the entire stack — from designing pixel-perfect
              interfaces to building the infrastructure behind them. Whether you
              need a complete product built from scratch or a specific piece of
              the puzzle, here is how I can help.
            </p>
          </header>
        </div>
      </div>

      <ServiceMarquee />

      {/* ── List ────────────────────────────────────────────────────────── */}
      <div className="pb-20 pt-20">
        <div className="mx-auto max-w-6xl px-6">
          <ServiceList services={services} headingLevel="h2" />

          {/* ── Guarantees ────────────────────────────────────────────── */}
          <section
            aria-labelledby="guarantees-heading"
            className="mt-24 border-t border-border pt-16"
          >
            <h2
              id="guarantees-heading"
              className="reveal mb-10 font-display text-2xl font-semibold tracking-tight text-fg md:text-3xl"
            >
              What every engagement includes
            </h2>
            <div className="stagger grid grid-cols-1 gap-5 md:grid-cols-3">
              {guarantees.map((item) => (
                <div
                  key={item.title}
                  className="glow-card rounded-2xl border border-border bg-raised p-6"
                >
                  <div
                    className="mb-4 flex h-9 w-9 items-center justify-center rounded-lg border border-border text-fg"
                    aria-hidden="true"
                  >
                    <svg width="15" height="15" viewBox="0 0 14 14" fill="none">
                      <path
                        d="M2 7.5l3.2 3.2L12 4"
                        stroke="currentColor"
                        strokeWidth="1.6"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                  <h3 className="mb-2 font-display text-base font-semibold tracking-tight text-fg">
                    {item.title}
                  </h3>
                  <p className="text-sm leading-relaxed text-muted">
                    {item.body}
                  </p>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>

      {/* FAQ — answers pre-sales questions, earns FAQ rich results */}
      <Faq />

      <CtaBand
        source="services"
        eyebrow="Not sure which one you need?"
        title="Tell me the problem — I'll tell you the fix."
        description="Most projects don't map neatly onto one service. Bring the problem to a free 30-minute call and I'll scope the smallest thing that actually solves it."
      />

      <BackToTop />
    </>
  );
}
