import type { Metadata } from 'next';
import Link from 'next/link';
import { getPosts } from '@/lib/data/posts';
import { getSite } from '@/lib/data/site';
import { siteUrl, defaultOgImages } from '@/lib/seo';
import type { Post } from '@/lib/types/content';
import CtaBand from '@/components/sections/CtaBand';
import ScrollProgress from '@/components/ui/ScrollProgress';
import BackToTop from '@/components/ui/BackToTop';

const pageDescription =
  'Practical articles on React, Next.js, GSAP, Tailwind CSS, automation, and running a small business online — written by a full-stack developer who ships.';

export async function generateMetadata(): Promise<Metadata> {
  const site = await getSite();

  return {
  title: 'Blog — Web Development & Business Insights',
  description: pageDescription,
  keywords: [
    'web development blog',
    'React tutorials',
    'Next.js guides',
    'GSAP animation',
    'Tailwind CSS',
    'frontend development',
    'business automation',
    'full-stack developer blog',
  ],
  alternates: { canonical: `${siteUrl}/blog` },
  openGraph: {
    title: 'Blog — Web Development Insights by Rahman',
    description:
      'Practical articles on React, Next.js, GSAP, and modern frontend engineering.',
    url: `${siteUrl}/blog`,
    type: 'website',
    images: defaultOgImages,
    // Social image generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    images: defaultOgImages,
    title: 'Blog — Web Development Insights by Rahman',
    description:
      'Practical articles on React, Next.js, GSAP, and modern frontend engineering.',
    site: site.social.twitterHandle,
    creator: site.social.twitterHandle,
  },
  };
}

const buildJsonLd = (sortedPosts: Post[]) => ({
  '@context': 'https://schema.org',
  '@type': 'Blog',
  '@id': `${siteUrl}/blog#blog`,
  name: 'Rahman — Web Development Blog',
  description: pageDescription,
  url: `${siteUrl}/blog`,
  inLanguage: 'en-US',
  isPartOf: { '@id': `${siteUrl}/#website` },
  author: { '@id': `${siteUrl}/#person` },
  publisher: { '@id': `${siteUrl}/#person` },
  blogPost: sortedPosts.map((p) => ({
    '@type': 'BlogPosting',
    headline: p.title,
    description: p.description,
    url: `${siteUrl}/blog/${p.slug}`,
    datePublished: p.updatedAt.toISOString(),
    dateModified: p.updatedAt.toISOString(),
    image: p.bannerImage.startsWith('/')
      ? `${siteUrl}${p.bannerImage}`
      : p.bannerImage,
    keywords: p.keywords.join(', '),
    author: { '@id': `${siteUrl}/#person` },
  })),
});

const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl },
    { '@type': 'ListItem', position: 2, name: 'Blog', item: `${siteUrl}/blog` },
  ],
};

export default async function BlogPage() {
  // `getPosts()` already returns newest-first.
  const sortedPosts = await getPosts();
  const jsonLd = buildJsonLd(sortedPosts);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <ScrollProgress />

      <div className="mx-auto max-w-3xl px-6 pb-24 pt-32">
        {/* ── Header ──────────────────────────────────────────────────── */}
        <header className="mb-16">
          <nav
            aria-label="Breadcrumb"
            className="mb-8 flex items-center gap-2 text-xs text-muted"
          >
            <Link href="/" className="transition-colors hover:text-fg">
              Home
            </Link>
            <span aria-hidden="true">/</span>
            <span className="text-fg">Blog</span>
          </nav>

          <h1 className="font-display text-5xl font-bold leading-tight tracking-tight text-fg md:text-6xl">
            Thoughts
          </h1>
          <p className="mt-4 max-w-lg leading-relaxed text-muted">
            I write about web development, performance, automation, and the
            craft of building things on the web.
          </p>
        </header>

        {/* ── Archive ─────────────────────────────────────────────────── */}
        <ol className="border-t border-border">
          {sortedPosts.map((post) => (
            <li key={post.slug}>
              <article className="group relative border-b border-border py-7 transition-[padding] duration-300 hover:pl-2">
                <div className="mb-2 flex items-center gap-3 text-xs text-muted">
                  <time dateTime={post.updatedAt.toISOString().split('T')[0]}>
                    {post.date}
                  </time>
                  <span aria-hidden="true">·</span>
                  <span>{post.readTime}</span>
                </div>

                <h2 className="font-display text-xl font-medium leading-snug tracking-tight text-fg md:text-2xl">
                  <Link
                    href={`/blog/${post.slug}`}
                    className="after:absolute after:inset-0 after:content-['']"
                  >
                    {post.title}
                  </Link>
                </h2>

                <p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted">
                  {post.description}
                </p>
              </article>
            </li>
          ))}
        </ol>
      </div>

      <CtaBand
        source="blog-index"
        eyebrow="Beyond the reading"
        title="Rather have it built than read about it?"
        description="Everything I write about here is work I do for clients. If you'd like it done for your business instead, a free 30-minute call is the fastest way to find out what it takes."
      />

      <BackToTop />
    </>
  );
}
