import type { Metadata } from 'next';
import Link from 'next/link';
import { posts } from '@/lib/data/posts';
import { siteUrl } from '@/lib/seo';

const sortedPosts = [...posts].sort(
  (a, b) => b.updatedAt.getTime() - a.updatedAt.getTime(),
);

export const metadata: Metadata = {
  title: 'Blog — Web Development Insights by Rahman',
  description:
    'Articles on React, Next.js, GSAP, Tailwind CSS, and modern web development. Practical guides written by a full-stack developer.',
  keywords: [
    'web development blog',
    'React tutorials',
    'Next.js guides',
    'GSAP animation',
    'Tailwind CSS',
    'frontend development',
    'full-stack developer blog',
  ],
  alternates: { canonical: `${siteUrl}/blog` },
  openGraph: {
    title: 'Blog — Web Development Insights by Rahman',
    description:
      'Practical articles on React, Next.js, GSAP, and modern frontend engineering.',
    url: `${siteUrl}/blog`,
    type: 'website',
    // Social image generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Blog — Web Development Insights by Rahman',
    description:
      'Practical articles on React, Next.js, GSAP, and modern frontend engineering.',
  },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Blog',
  name: 'Rahman — Web Development Blog',
  description: metadata.description,
  url: `${siteUrl}/blog`,
  author: {
    '@type': 'Person',
    name: 'Rahman',
    url: siteUrl,
  },
  blogPost: sortedPosts.map((p) => ({
    '@type': 'BlogPosting',
    headline: p.title,
    description: p.description,
    url: `${siteUrl}/blog/${p.slug}`,
    datePublished: p.updatedAt.toISOString(),
    keywords: p.keywords.join(', '),
  })),
};

export default function BlogPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="min-h-screen pt-32 pb-20">
        <div className="max-w-3xl mx-auto px-6">
          <header className="mb-16">
            <p className="text-xs font-medium tracking-widest uppercase text-[#8a8a8a] mb-4">
              Writing
            </p>
            <h1 className="font-display text-5xl md:text-6xl font-bold text-[#fafafa] tracking-tight leading-tight">
              Thoughts
            </h1>
            <p className="text-[#8a8a8a] mt-4 leading-relaxed max-w-lg">
              I write about web development, performance, and the craft of
              building things on the web.
            </p>
          </header>

          <ol className="divide-y divide-[#242424]">
            {sortedPosts.map((post) => (
              <li key={post.slug}>
                <Link
                  href={`/blog/${post.slug}`}
                  className="group flex flex-col gap-2 py-8 hover:pl-2 transition-all duration-200"
                >
                  <div className="flex items-center gap-3 text-xs text-[#8a8a8a]">
                    <time dateTime={post.updatedAt.toISOString().split('T')[0]}>
                      {post.date}
                    </time>
                    <span aria-hidden="true">·</span>
                    <span>{post.readTime}</span>
                  </div>

                  <h2 className="font-display text-xl font-semibold text-[#fafafa] tracking-tight leading-snug group-hover:text-[#fafafa] transition-colors">
                    {post.title}
                  </h2>

                  <p className="text-sm text-[#8a8a8a] leading-relaxed line-clamp-2">
                    {post.description}
                  </p>

                  <div className="flex flex-wrap gap-2 mt-1">
                    {post.tags.map((tag) => (
                      <span
                        key={tag}
                        className="text-xs px-2.5 py-0.5 rounded-full border border-[#242424] text-[#8a8a8a]"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </Link>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </>
  );
}
