import type { Metadata, Viewport } from 'next';
import { Inter, Inter_Tight, Dancing_Script } from 'next/font/google';
import './globals.css';
import BookingModalProvider from '@/components/ui/BookingModalProvider';
import ContactFormS from '@/components/ui/ContactFormS';
import StickyCta from '@/components/layout/StickyCta';
import { getSite } from '@/lib/data/site';
import { getServices } from '@/lib/data/services';
import type { SiteConfig, Service } from '@/lib/types/content';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});

const interTight = Inter_Tight({
  variable: '--font-inter-tight',
  subsets: ['latin'],
  display: 'swap',
});

const dancingScript = Dancing_Script({
  variable: '--font-cursive',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://yourname.dev';

const rootDescription =
  'Freelance full-stack developer building fast, accessible web apps, custom CRMs, e-commerce stores, APIs, and AI automations with Next.js and TypeScript.';

/** Async because `twitter.site`/`twitter.creator` come from the editable site
 *  config. Next still evaluates this once at build for a static route, so this
 *  costs nothing at request time. */
export async function generateMetadata(): Promise<Metadata> {
  const site = await getSite();

  return {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Rahman — Full-Stack Web Developer',
    template: '%s | Rahman',
  },
  description: rootDescription,
  applicationName: 'Rahman — Software Developer',
  authors: [{ name: 'Rahman', url: siteUrl }],
  creator: 'Rahman',
  publisher: 'Rahman',
  category: 'technology',
  keywords: [
    'full-stack developer',
    'freelance web developer',
    'Next.js developer',
    'React developer',
    'TypeScript',
    'custom CRM development',
    'API development',
    'web application development',
    'AI automation',
  ],
  // Stops iOS Safari turning numbers in body copy into blue phone links,
  // which otherwise wrecks the dark UI.
  formatDetection: { telephone: false, email: false, address: false },
  openGraph: {
    title: 'Rahman — Full-Stack Web Developer',
    description: rootDescription,
    url: siteUrl,
    siteName: 'Rahman',
    // Social image is generated by app/opengraph-image.tsx (next/og)
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Rahman — Full-Stack Web Developer',
    description: rootDescription,
    site: site.social.twitterHandle,
    creator: site.social.twitterHandle,
    // Twitter falls back to the generated og:image
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      // Let Google use full-size image previews and longer snippets —
      // both materially improve click-through from search.
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  alternates: { canonical: '/' },
  };
}

export const viewport: Viewport = {
  themeColor: '#f5f2ec',
  colorScheme: 'light',
  width: 'device-width',
  initialScale: 1,
};

// Person schema — enriched for richer knowledge-panel / rich-result eligibility.
const buildPersonJsonLd = (site: SiteConfig) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  '@id': `${siteUrl}/#person`,
  name: 'Rahman',
  jobTitle: 'Software Developer',
  description: rootDescription,
  url: siteUrl,
  image: `${siteUrl}/rahman.jpeg`,
  email: `mailto:${site.social.email}`,
  telephone: `+${site.social.phoneDigits}`,
  address: {
    '@type': 'PostalAddress',
    addressLocality: site.location.city,
    addressCountry: site.location.country,
  },
  knowsAbout: [
    'Web Development',
    'React',
    'Next.js',
    'TypeScript',
    'Node.js',
    'UI/UX Design',
    'API Development',
    'Custom CRM Development',
    'E-Commerce Development',
    'Workflow Automation',
  ],
  sameAs: [site.social.github, site.social.linkedin, site.social.twitter],
});

// WebSite schema — helps search engines understand the site entity.
const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${siteUrl}/#website`,
  name: 'Rahman — Software Developer',
  description: rootDescription,
  url: siteUrl,
  publisher: { '@id': `${siteUrl}/#person` },
  inLanguage: 'en-US',
};

// ProfessionalService — the schema that actually describes the *business*.
// The offer catalogue is generated from the real service list, so it can never
// drift out of sync with what the site says it sells.
const buildBusinessJsonLd = (site: SiteConfig, services: Service[]) => ({
  '@context': 'https://schema.org',
  '@type': 'ProfessionalService',
  '@id': `${siteUrl}/#business`,
  name: 'Rahman — Software Development',
  description: rootDescription,
  url: siteUrl,
  image: `${siteUrl}/rahman.jpeg`,
  email: `mailto:${site.social.email}`,
  telephone: `+${site.social.phoneDigits}`,
  founder: { '@id': `${siteUrl}/#person` },
  address: {
    '@type': 'PostalAddress',
    addressLocality: site.location.city,
    addressCountry: site.location.country,
  },
  areaServed: 'Worldwide',
  availableLanguage: ['English', 'Hindi'],
  sameAs: [site.social.github, site.social.linkedin, site.social.twitter],
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'Software development services',
    itemListElement: services.map((service) => ({
      '@type': 'Offer',
      itemOffered: {
        '@type': 'Service',
        name: service.title,
        description: service.shortDesc,
        url: `${siteUrl}/services/${service.slug}`,
      },
    })),
  },
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Both reads are cached and tag-invalidated, so this is a memory hit on
  // every render after the first.
  const [site, services] = await Promise.all([getSite(), getServices()]);

  const personJsonLd = buildPersonJsonLd(site);
  const businessJsonLd = buildBusinessJsonLd(site, services);

  return (
    <html
      lang="en"
      className={`${inter.variable} ${interTight.variable} ${dancingScript.variable}`}
    >
      <body className="min-h-screen flex flex-col bg-bg text-fg antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(businessJsonLd) }}
        />

        {/* Keyboard users land here first — invisible until focused */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[200] focus:rounded-full focus:bg-fg focus:px-5 focus:py-2.5 focus:text-sm focus:font-semibold focus:text-bg"
        >
          Skip to content
        </a>

        <BookingModalProvider site={site}>
          {children}
          <StickyCta site={site} />
        </BookingModalProvider>
        <ContactFormS />
      </body>
    </html>
  );
}
