import type { Metadata, Viewport } from 'next';
import { Inter, Inter_Tight, Dancing_Script } from 'next/font/google';
import './globals.css';
import BookingModalProvider from '@/components/ui/BookingModalProvider';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});

const interTight = Inter_Tight({
  variable: '--font-inter-tight',
  subsets: ['latin'],
  display: 'swap',
});

const dancingScript = Dancing_Script({
  variable: '--font-cursive',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? 'https://yourname.dev'
  ),
  title: {
    default: 'Rahman — Full-Stack Developer',
    template: '%s | Rahman',
  },
  description:
    'Full-Stack Developer building fast, accessible, and beautifully crafted web products. Available for freelance.',
  openGraph: {
    title: 'Rahman — Full-Stack Developer',
    description:
      'Full-Stack Developer building fast, accessible, and beautifully crafted web products.',
    url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://yourname.dev',
    siteName: 'Rahman',
    // Social image is generated by app/opengraph-image.tsx (next/og)
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Rahman — Full-Stack Developer',
    description:
      'Full-Stack Developer building fast, accessible, and beautifully crafted web products.',
    // Twitter falls back to the generated og:image
  },
  robots: { index: true, follow: true },
  alternates: { canonical: '/' },
};

export const viewport: Viewport = {
  themeColor: '#0a0a0a',
  colorScheme: 'dark',
  width: 'device-width',
  initialScale: 1,
};

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://yourname.dev';

// Person schema — enriched for richer knowledge-panel / rich-result eligibility.
const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  '@id': `${siteUrl}/#person`,
  name: 'Rahman',
  jobTitle: 'Full-Stack Developer',
  description:
    'Full-Stack Developer building fast, accessible, and beautifully crafted web products.',
  url: siteUrl,
  image: `${siteUrl}/rahman.jpeg`,
  email: 'mailto:hello@yourname.dev',
  knowsAbout: [
    'Web Development',
    'React',
    'Next.js',
    'TypeScript',
    'Node.js',
    'UI/UX Design',
    'API Development',
  ],
  sameAs: [
    'https://github.com/rahman',
    'https://linkedin.com/in/rahman',
  ],
};

// WebSite schema — helps search engines understand the site entity.
const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${siteUrl}/#website`,
  name: 'Rahman — Full-Stack Developer',
  url: siteUrl,
  publisher: { '@id': `${siteUrl}/#person` },
  inLanguage: 'en-US',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${interTight.variable} ${dancingScript.variable}`}
    >
      <body className="min-h-screen flex flex-col bg-[#0a0a0a] text-[#fafafa] antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <BookingModalProvider>{children}</BookingModalProvider>
      </body>
    </html>
  );
}
