import type { Metadata } from 'next';
import { defaultSite } from '@/lib/site';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://yourname.dev';
const siteName = 'Rahman — Software Developer';
const defaultDescription =
  'Software Developer building fast, accessible, and beautifully crafted web products. Available for freelance.';

/**
 * The site-wide social card — the 1200×630 image generated by
 * `app/opengraph-image.tsx`.
 *
 * **Spread this into every `openGraph` and `twitter` block that does not set
 * its own `images`.** It is not optional boilerplate.
 *
 * Next injects the `opengraph-image` file into the root segment's metadata
 * automatically, but a nested segment that declares an `openGraph` object
 * *replaces the parent's entire `openGraph`* — including those injected
 * images. So a page that sets only `title` and `description` silently ends up
 * with no `og:image` at all, and every link to it unfurls as a bare text row.
 * That is not a warning or a build error; the only symptom is a sad-looking
 * link, which is why it went unnoticed.
 *
 * Pages with their own artwork (blog posts, service and project detail pages)
 * override this with their banner and should keep doing so — but see the note
 * in `content/CONTENT_GUIDE.md` about keeping those files small enough for
 * WhatsApp to fetch.
 */
export const defaultOgImages = [
  {
    url: `${siteUrl}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: siteName,
    type: 'image/png',
  },
];

/**
 * Turn a stored content image path into an absolute URL.
 *
 * Paths authored in `content/**` are relative to `public/` (`/blog/foo.jpg`),
 * but `og:image` and JSON-LD both require an absolute URL — scrapers drop a
 * relative one silently. Values that are already absolute (an R2 / CDN URL
 * written by the admin panel's media library) pass through untouched.
 */
export function absoluteImageUrl(path: string): string {
  return path.startsWith('/') ? `${siteUrl}${path}` : path;
}

/** The image fields every content entry may carry. */
export interface ContentImages {
  /** Purpose-built 1200×630 share card. Never rendered on the page. */
  ogImage?: string;
  ogAlt?: string;
  /** The in-page banner shown at the top of the entry. */
  bannerImage?: string;
  bannerAlt?: string;
}

/**
 * The share card for a content entry: the dedicated `ogImage` when the author
 * supplied one, otherwise the in-page banner.
 *
 * The two are separate because they are different jobs. A banner is cropped to
 * a wide strip and is read at whatever size the layout gives it; a share card
 * is a fixed 1200×630 tile that has to survive being scaled into a WhatsApp
 * thumbnail, so it usually wants larger type and a tighter crop. Falling back
 * to the banner keeps `ogImage` fully optional — every entry authored before
 * this field existed behaves exactly as it did.
 *
 * Returns `undefined` only when the entry has neither, which is possible for
 * projects; callers should fall back to `defaultOgImages` rather than emitting
 * an `openGraph` block with no image at all (see the note above).
 */
export function socialImage(
  source: ContentImages,
  fallbackAlt: string,
): { url: string; alt: string } | undefined {
  const path = source.ogImage ?? source.bannerImage;
  if (!path) return undefined;
  // `ogAlt` describes the share card, so it only applies when that card is the
  // image actually being used.
  const alt = (source.ogImage ? source.ogAlt : undefined) ?? source.bannerAlt ?? fallbackAlt;
  return { url: absoluteImageUrl(path), alt };
}

/**
 * The image for the JSON-LD graph — banner first, share card only as a
 * fallback. This is the opposite priority to `socialImage()` on purpose:
 * schema.org `image` means "the image that represents this content", and Google
 * expects to find it on the page. The share card is marketing artwork that no
 * visitor ever sees, so it is the second choice here.
 */
export function structuredDataImage(source: ContentImages): string | undefined {
  const path = source.bannerImage ?? source.ogImage;
  return path ? absoluteImageUrl(path) : undefined;
}

/**
 * Synchronous metadata defaults. Uses `defaultSite` rather than the live
 * config on purpose — it is not async, so it cannot read the database. Pages
 * that need the editable site config build their metadata in their own
 * `generateMetadata()` instead.
 */
export function buildMetadata(overrides: Partial<Metadata> = {}): Metadata {
  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: siteName,
      template: `%s | Rahman`,
    },
    description: defaultDescription,
    openGraph: {
      title: siteName,
      description: defaultDescription,
      url: siteUrl,
      siteName,
      // Social image generated by app/opengraph-image.tsx
      locale: 'en_US',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: siteName,
      description: defaultDescription,
      site: defaultSite.social.twitterHandle,
      creator: defaultSite.social.twitterHandle,
    },
    robots: { index: true, follow: true },
    alternates: { canonical: '/' },
    ...overrides,
  };
}

export { siteUrl, siteName, defaultDescription };
