import type { Metadata } from 'next';
import { defaultSite } from '@/lib/site';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://yourname.dev';
const siteName = 'Rahman — Software Developer';
const defaultDescription =
  'Software Developer building fast, accessible, and beautifully crafted web products. Available for freelance.';

/**
 * The site-wide social card — the 1200×630 image generated by
 * `app/opengraph-image.tsx`.
 *
 * **Spread this into every `openGraph` and `twitter` block that does not set
 * its own `images`.** It is not optional boilerplate.
 *
 * Next injects the `opengraph-image` file into the root segment's metadata
 * automatically, but a nested segment that declares an `openGraph` object
 * *replaces the parent's entire `openGraph`* — including those injected
 * images. So a page that sets only `title` and `description` silently ends up
 * with no `og:image` at all, and every link to it unfurls as a bare text row.
 * That is not a warning or a build error; the only symptom is a sad-looking
 * link, which is why it went unnoticed.
 *
 * Pages with their own artwork (blog posts, service and project detail pages)
 * override this with their banner and should keep doing so — but see the note
 * in `content/CONTENT_GUIDE.md` about keeping those files small enough for
 * WhatsApp to fetch.
 */
export const defaultOgImages = [
  {
    url: `${siteUrl}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: siteName,
    type: 'image/png',
  },
];

/**
 * Synchronous metadata defaults. Uses `defaultSite` rather than the live
 * config on purpose — it is not async, so it cannot read the database. Pages
 * that need the editable site config build their metadata in their own
 * `generateMetadata()` instead.
 */
export function buildMetadata(overrides: Partial<Metadata> = {}): Metadata {
  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: siteName,
      template: `%s | Rahman`,
    },
    description: defaultDescription,
    openGraph: {
      title: siteName,
      description: defaultDescription,
      url: siteUrl,
      siteName,
      // Social image generated by app/opengraph-image.tsx
      locale: 'en_US',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: siteName,
      description: defaultDescription,
      site: defaultSite.social.twitterHandle,
      creator: defaultSite.social.twitterHandle,
    },
    robots: { index: true, follow: true },
    alternates: { canonical: '/' },
    ...overrides,
  };
}

export { siteUrl, siteName, defaultDescription };
