import type { Metadata } from "next";
import Link from "next/link";
import { getProjects } from "@/lib/data/projects";
import type { Project } from "@/lib/types/content";
import { siteUrl } from "@/lib/seo";
import { getSite } from "@/lib/data/site";
import ProjectCard from "@/components/ui/ProjectCard";
import CtaBand from "@/components/sections/CtaBand";
import ScrollProgress from "@/components/ui/ScrollProgress";
import BackToTop from "@/components/ui/BackToTop";

const pageDescription =
  "Case studies of software I've built: a real-time e-commerce platform, a multi-tenant SaaS analytics dashboard, and a headless portfolio CMS. The problem, the approach, and what actually shipped.";

export async function generateMetadata(): Promise<Metadata> {
  const site = await getSite();

  return {
  title: "Projects — Case Studies of Shipped Work",
  description: pageDescription,
  keywords: [
    "web developer portfolio case studies",
    "full-stack developer projects",
    "Next.js project case study",
    "custom e-commerce development",
    "multi-tenant SaaS dashboard",
    "freelance developer work samples",
  ],
  alternates: { canonical: `${siteUrl}/projects` },
  openGraph: {
    title: "Projects — Case Studies by Rahman",
    description:
      "The problem, the approach, and the outcome for each thing I've built. Not screenshots — the engineering decisions behind them.",
    url: `${siteUrl}/projects`,
    type: "website",
    // Social image generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Projects — Case Studies by Rahman",
    description:
      "The problem, the approach, and the outcome for each thing I've built. Not screenshots — the engineering decisions behind them.",
    site: site.social.twitterHandle,
    creator: site.social.twitterHandle,
  },
  };
}

const buildJsonLd = (projects: Project[]) => ({
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "@id": `${siteUrl}/projects#page`,
  name: "Projects — Rahman Software Developer",
  description: pageDescription,
  url: `${siteUrl}/projects`,
  isPartOf: { "@id": `${siteUrl}/#website` },
  about: { "@id": `${siteUrl}/#person` },
  inLanguage: "en-US",
  mainEntity: {
    "@type": "ItemList",
    itemListElement: projects.map((p, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: p.title,
      description: p.shortDesc,
      url: `${siteUrl}/projects/${p.slug}`,
    })),
  },
});

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
    {
      "@type": "ListItem",
      position: 2,
      name: "Projects",
      item: `${siteUrl}/projects`,
    },
  ],
};

export default async function ProjectsPage() {
  const [projects, site] = await Promise.all([getProjects(), getSite()]);
  const jsonLd = buildJsonLd(projects);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <ScrollProgress />

      {/* ── Hero ────────────────────────────────────────────────────────── */}
      <div className="relative overflow-hidden pt-32 pb-16">
        <div className="aurora" aria-hidden="true" />
        <div className="grid-bg" aria-hidden="true" />

        <div className="relative mx-auto max-w-6xl px-6">
          <nav
            aria-label="Breadcrumb"
            className="mb-8 flex items-center gap-2 text-xs text-muted"
          >
            <Link href="/" className="transition-colors hover:text-fg">
              Home
            </Link>
            <span aria-hidden="true">/</span>
            <span className="text-fg">Projects</span>
          </nav>

          <header className="max-w-3xl">
            <p className="mb-4 text-xs font-medium uppercase tracking-widest text-muted">
              Selected Work
            </p>
            <h1 className="mb-6 font-display text-5xl font-bold leading-tight tracking-tight text-fg md:text-6xl">
              Projects
            </h1>
            <p className="text-lg leading-relaxed text-muted">
              Each of these is a case study rather than a screenshot — the
              problem the business actually had, the decisions I made, the
              trade-offs I got wrong, and what shipped in the end. If you want
              to know how I think before you hire me, this is the honest
              version.
            </p>
          </header>
        </div>
      </div>

      {/* ── Grid ────────────────────────────────────────────────────────── */}
      <div className="pb-20">
        <div className="mx-auto max-w-6xl px-6">
          <div className="stagger grid grid-cols-1 gap-6 md:grid-cols-2 ">
            {projects.map((project, i) => (
              <ProjectCard
                key={project.slug}
                project={project}
                index={i}
                headingLevel="h2"
              />
            ))}
          </div>

          {/* GitHub, demoted to a footnote — the case studies are the pitch */}
          <div className="mt-14 border-t border-border pt-10 text-center">
            <p className="mb-3 text-sm text-muted">
              Client work under NDA and smaller experiments don&apos;t get a
              write-up here.
            </p>
            <a
              href={site.social.github}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm text-fg"
            >
              <span className="link-sweep">More on GitHub ↗</span>
            </a>
          </div>
        </div>
      </div>

      <CtaBand
        source="projects"
        eyebrow="Your project could be next"
        title="Tell me what you're trying to build."
        description="Bring the problem — a rough idea is enough. Thirty minutes on a call and you'll leave with a scope, a timeline, and a written quote, whether or not you hire me."
      />

      <BackToTop />
    </>
  );
}
